import { JWT } from 'google-auth-library';

export const auth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.SHEETS_EMAIL!,
  key: process.env.SHEETSKEY!,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});
