import { JWT } from 'google-auth-library';

/**
 * Authentication object using JWT (JSON Web Token) for Google Sheets API.
 * Uses service account credentials generated by Google.
 * @see {@link https://developers.google.com/sheets/api/guides/authorizing} Authentication
 */
export const auth = new JWT({
  // Environment variable values here are copied from service account credentials generated by Google.
  // See "Authentication" section in docs for more info.
  email: process.env.SHEETS_EMAIL!, // Service account email
  key: process.env.SHEETSKEY!, // Service account private key
  scopes: ['https://www.googleapis.com/auth/spreadsheets'], // Scopes required for accessing Google Sheets API
});
